### ISSUE TITLE
Recursive calls to registerPartial missing callback.

### ISSUE THREAD

**Issue by ghost** [71104/jquery-handlebars#2]
When running this plugin with partials following the documentation, I see "Uncaught TypeError: undefined is not a function."

![snag-9-19-2013-11-15-00001](https://f.cloud.github.com/assets/4366451/1174863/49be9526-214f-11e3-8232-fa8d6ba57190.png)

**Comment by 71104** [comment]
Thank you for reporting, I'll work on this.

**Comment by 71104** [comment]
Fixed, [version 1.1](https://raw.github.com/71104/jquery-handlebars/1.1.1/bin/jquery-handlebars-1.1.1.min.js) released.
