### ISSUE TITLE
Clarification on use

### ISSUE THREAD

**Issue by angelxmoreno** [71104/jquery-handlebars#8]
Is this how I am supposed to use the function?

``` HTML
<div id="placeholder"></div>

<script id="snippet" type="text/x-handlebars-template">
<div>
    <p>Hello there {{dude.name}}!</p>
    <p>Heard your favorite movie was {{dude.movie}}</p>
</div>

</script>

$(document).ready(function () {
    var dude = {movie:'Le Matrix',name:'Le Neno'};
    $('#placeholder').render('snippet', dude);    
});
```

The end result I am expecting is 

``` HTML
<div id="placeholder">
    <div>
        <p>Hello there Le Neo!</p>
        <p>Heard your favorite movie was Le Matrix</p>
    </div>
</div>
```

**Comment by 71104** [comment]
In order for your code to function there must be a "snippet.handlebars" file containing the template:

``` html
<div>
    <p>Hello there {{dude.name}}</p>
    <p>Heard your favorite movie was {{dude.movie}}</p>
</div>
```

Then, in the main page, you can do:

``` html
<html>
...
<body>
    <div id="placeholder"></div>
    <script>
$(function () {
    var dude = {movie:'Le Matrix',name:'Le Neno'};
    $('#placeholder').render('snippet', dude);
});
    </script>
</body>
</html>
```

**Comment by 71104** [comment]
@angelxmoreno I see right now what you tried to do there.

Sorry but inline templates in the page are not supported yet, you need to write all your templates as separate files. Everything is explained in the main project page: http://71104.github.io/jquery-handlebars/

**Comment by angelxmoreno** [comment]
Would be nice to support inline templates but I see how calling what i need only when I need it would decrease load time. Let's point that out in the readme to clarify since it could be assumed that the plugin should handle inline templates.
